using System;
using System.Collections.Generic;
using System.Text;

namespace BSuiteE2ERegressionTest.Models.BSuite.DesktopPortal
{
    public static class UIMap
    {
        public static readonly Dictionary<string, (string resourceName, string windowTitle)> UIPageMap = new Dictionary<string, (string, string)>()
        {
            //Call Centre
                {"Admin", ("adminmenulayout","Admin")},
                {"Call Centre", ("calldeskmenulayout","CallDesk")},
                {"Add Task", ("calldesk", "CallDesk")},
                {"Add Task - FieldTask", ("calldesk", "CallDesk")},
                {"PreStart", ("prestart", "preStart")},
                {"Import FieldTasks",("bulkload/tasks","BSuite")},
                {"BSuite",("bulkload/tasks","BSuite")},
                {"Task Status Screen",("fieldtaskstatus","FieldTaskStatus")},
                {"A - FieldTaskEdit",("fieldtaskstatus/edit","fieldtaskstatusedit")},
                {"FieldTaskAuditLog",("/fieldtaskauditlog/fieldtaskedit/fieldtask","FieldTaskAuditLog")},
                {"Tasks by Watch List", ("taskbytech","TechTask")},
                {"Admin Warehouse", ("storagelocation", "Warehouse")},
                {"Reports", ("reportsmenulayout","Reports")},
                {"Prestart Desktop", ("report/prestartdesktop","Prestart Desktop")},
                {"Edit Watch List Preference", ("taskbytech","TechTask")},
                {"PreStart link", ("taskbytech", "taskByTech")},
                {"Personnel", ("person", "Person")},
                {"Cause Categories", ("admin/causecategorytype", "CauseCategory")},
                {"Service Plan", ("serviceplan", "serviceplan")},
                {"View Service Plan", ("serviceplan/view", "ServicePlan")},
                {"Action Type", ("admin/actiontype", "ActionType")},
                {"Region", ("country", "Country")},
                {"Clone User Account", ("admin/createuser", "CreateUser")},
                {"Admin Part Types", ("parttypes", "PartType")},
                {"Task Status", ("task/logistics", "TaskStatus")},
                {"Purchase Orders", ("purchaseorder", "PurchaseOrder")},
                {"Reconcile Purchase Order", ("purchaseorder/reconcile", "ReconcilePurchaseOrder")},
                {"Worm", ("report/worm","Worm")},
                {"Worm Graph", ("ajax/?method=worm&workTypes","Bsuite.net Worm Graph")},
                {"Bad Dates Report", ("report/baddatesdata","BadDateData")},

        };

        public static readonly List<(string screen, string elementName, string elementId)> UIElementMap = new List<(string, string, string)>(){
            //Call Centre 
            ("calldesk", "Site", "ctl0_MainContent_SiteList"),
            ("calldesk", "Contract/WorkType", "ctl0_MainContent_WorkTypeList"),
            ("calldesk", "Add Task", "ctl0_MainContent_AddFieldTaskButton" ),
            ("calldesk", "Site", "ctl0_MainContent_SiteList" ),
            ("calldesk", "Contact", "ctl0_MainContent_SiteContact" ),
            ("calldesk", "App. Start Time", "ctl0_MainContent_appointmentStartTime" ),
            ("calldesk", "App. Start Hour", "ctl0_MainContent_fromHourBox" ),
            ("calldesk", "App. Start Minute", "ctl0_MainContent_fromMinuteBox" ),
            ("calldesk", "App. End Time", "ctl0_MainContent_appointmentEndTime" ),
            ("calldesk", "App. End Hour", "ctl0_MainContent_toHourBox" ),
            ("calldesk", "App. End Minute", "ctl0_MainContent_toMinuteBox" ),
            ("calldesk", "Serial Number", "ctl0_MainContent_SerialNumber" ),
            ("calldesk", "Part", "ctl0_MainContent_PartTypes" ),
            ("calldesk", "Part Status", "ctl0_MainContent_EquipmentStatusList" ),
            ("calldesk", "Position", "ctl0_MainContent_Position" ),
            ("calldesk", "Similar Tasks", "ctl0_MainContent_SimilarTasks" ),
            ("calldesk", "Billable", "ctl0_MainContent_Billable" ),
            ("calldesk", "Task Status", "ctl0_MainContent_FieldTaskStatusList" ),
            ("calldesk", "Priority", "ctl0_MainContent_PriorityList" ),
            ("calldesk", "Client Ref #", "ctl0_MainContent_ClientReferenceNumber" ),
            ("calldesk", "Problem Category", "ctl0_MainContent_ProblemCategoryList" ),
            ("calldesk", "Problem Code", "ctl0_MainContent_ProblemList" ),
            ("calldesk", "Problem Desc", "ctl0_MainContent_ProblemDescription" ),
            ("calldesk", "Client Notes", "ctl0_MainContent_ClientNotes" ),
            ("calldesk", "Call Centre Notes", "ctl0_MainContent_CallDeskNotes" ),
            ("calldesk", "Save", "ctl0_MainContent_saveButton" ),
            ("calldesk", "Task ##", "ctl0_MainContent_FieldTaskNumber"),
            ("calldesk", "TaskNumber", "//span[@id='ctl0_MainContent_FieldTaskNumber']/b/a"),
            ("calldesk", "Details of Client Targets For This Task", "ctl0_MainContent_FieldTaskTargets" ),
            ("calldesk", "Finish", "ctl0_MainContent_CancelFieldTask" ),
            ("calldesk", "Add Another", "ctl0_MainContent_AnotherFieldTask" ),
            ("calldesk", "TaskNumber", "//span[@id='ctl0_MainContent_FieldTaskNumber']/b/a"),
            ("prestart", "Lets complete your Pre Start Checklist for today ", "ctl0_MainContent_AnotherFieldTask" ),
            ("prestart", "Submit", "ctl0_MainContent_SubmitButton" ),
            ("bulkload/tasks", "WorkType", "ctl0_MainContent_workType"),
            ("bulkload/tasks", "File", "ctl0_MainContent_FileUploader"),
            ("bulkload/tasks", "Upload", "ctl0$MainContent$ctl2"),
            ("bulkload/tasks", "Yes", "//div[@id='continuePanel']/input[1]"),
            ("fieldtaskstatus", "Task No", "ctl0_MainContent_taskNumber"),
            ("fieldtaskstatus", "Client Ref", "ctl0_MainContent_clientRefNumber"),
            ("fieldtaskstatus", "Serial Number", "ctl0_MainContent_serialNumber"),
            ("fieldtaskstatus", "Search Field Tasks", "ctl0_MainContent_search"),
            ("fieldtaskstatus", "Search Tasks Result", "//table[@class='DataList']/tbody/tr[1]/td[1]"),
            ("fieldtaskstatus", "Search Client Ref", "//table[@class='DataList']/tbody/tr[1]/td[2]"),
            ("fieldtaskstatus", "Tasks Result Table", "//table[@class='DataList']/tbody"),
            ("fieldtaskstatus", "Tasks Result Table Header", "//table[@class='DataList']/thead"),
            ("fieldtaskstatus/edit", "Task No Status", "ctl0_MainContent_TaskNumberLabel"),
            ("fieldtaskstatus/edit", "Audit Log", "ctl0_MainContent_AuditLogButton"),
            ("fieldtaskstatus/edit", "Task Status", "ctl0_MainContent_FieldTaskStatusList"),
            ("fieldtaskstatus/edit", "Technician", "ctl0_MainContent_TechnicianList"),
            ("fieldtaskstatus/edit", "Save", "ctl0_MainContent_SaveButton"),
            ("fieldtaskstatus/edit", "Yes", "ctl0_MainContent_CancelConfirmYes"),
            ("storagelocation", "Warehouse Name", "ctl0_MainContent_SearchName" ),
            ("storagelocation", "Search", "ctl0_MainContent_SearchButton" ),
            ("storagelocation", "Show Details","//span[@id='ctl0_MainContent_storageLocationList']/table/tbody/tr//select" ),
            ("storagelocation", "Cancel","ctl0$MainContent$ctl4" ),
            ("storagelocation", "Alias","ctl0_MainContent_SearchAlias" ),
            ("storagelocation", "Show Warehouses Under","ctl0_MainContent_showLocationBtn" ),
            ("storagelocation", "Reset","//span[@id='ctl0_MainContent_TreeLabel']/input" ),            
            ("report/prestartdesktop", "fromDateReport", "ctl0_MainContent_fromDateReport" ),
            ("report/prestartdesktop", "toDateReport", "ctl0_MainContent_toDateReport" ),
            ("report/prestartdesktop", "Output To CSV", "//input[@value='Output To CSV']" ),
            ("taskbytech", "Edit Preferences", "ctl0_MainContent_AddButton" ),
            ("taskbytech", "All Technicians", "ctl0_MainContent_outTechList" ),
            ("taskbytech", "Technicians currently on watch list", "ctl0_MainContent_inTechList" ),
            ("taskbytech", "Add Technicians", "ctl0_MainContent_addTechBtn" ),
            ("taskbytech", "Remove Technicians", "ctl0_MainContent_removeTechBtn" ),
            ("taskbytech", "Unassigned Tasks By State", "ctl0_MainContent_unassignedStateList" ),
            ("taskbytech", "Unassigned Tasks By WorkType", "ctl0_MainContent_unassignedWorkTypeList" ),
            ("taskbytech", "Unassigned Add State WorkType", "ctl0_MainContent_addUnassignedBtn" ),
            ("taskbytech", "Pending Tasks By State", "ctl0_MainContent_pendingStateList" ),
            ("taskbytech", "Pending Tasks By WorkType", "ctl0_MainContent_pendingWorkTypeList" ),
            ("taskbytech", "Pending Add State WorkType", "ctl0_MainContent_addPendingBtn" ),
            ("taskbytech", "Save and Update", "ctl0_MainContent_EditButton" ),
            ("taskbytech", "Unassigned Panel", "//div[@id='ctl0_MainContent_UnassignedPanel']/table/tbody" ),
            ("taskbytech", "All Agents", "ctl0_MainContent_outAgentList" ),
            ("taskbytech", "Agents currently on watch list", "ctl0_MainContent_inAgentList" ),
            ("taskbytech", "Add Agents", "ctl0_MainContent_addAgentBtn" ),
            ("taskbytech", "Remove Agents", "ctl0_MainContent_removeAgentBtn" ),
            ("taskbytech", "Assigned to Techs","ctl0_MainContent_ShowTechLabel" ),
            ("taskbytech", "Assigned to Agents", "ctl0_MainContent_ShowAgentBtn" ),
            ("taskbytech", "Unassigned", "ctl0_MainContent_ShowUnassignedBtn" ),
            ("taskbytech", "Pending", "ctl0_MainContent_ShowPendingBtn" ),
            ("taskbytech", "Full Screen Mode", "ctl0_MainContent_toggleDisplayButton" ),
            ("taskbytech", "Edit Preferences", "ctl0_MainContent_AddButton" ),
            ("taskbytech", "Show Legend", "ctl0_MainContent_LegendButton" ),
            ("taskbytech", "Assigned to Techs Table", "//div[@id='ctl0_MainContent_TechPanel']/table/tbody/tr" ),
            ("taskbytech", "Assigned to Agents Table", "//div[@id='ctl0_MainContent_AgentPanel']/table/tbody/tr" ),
            ("taskbytech", "Unassigned Table", "//div[@id='ctl0_MainContent_UnassignedPanel']/table/tbody/tr" ),
            ("taskbytech", "Pending Table", "//div[@id='ctl0_MainContent_PendingPanel']/table/tbody/tr" ),
            ("fieldtaskstatus", "View Status Legend", "ctl0_MainContent_changeLegendVisibility"),
            ("fieldtaskstatus", "Change Column Views", "ctl0_MainContent_changeColumnVisibilities"),
            ("fieldtaskstatus", "State", "//label[text()='State']/preceding-sibling::input"),
            ("fieldtaskstatus", "APP_END", "//label[text()='APP_END']/preceding-sibling::input"),
            ("fieldtaskstatus", "save view", "ctl0_MainContent_saveColumnBtn"),
            ("person", "Add Person", "ctl0_MainContent_AddButton"),
            ("person", "First Name", "ctl0_MainContent_FirstName"),
            ("person", "Last Name", "ctl0_MainContent_LastName"),
            ("person", "Email", "ctl0_MainContent_Email"),
            ("person", "Company", "ctl0_MainContent_CompanyDataList"),           
            ("person", "AddressName", "ctl0_MainContent_Person_Address_AddressName"),
            ("person", "Address_Line 1", "ctl0_MainContent_Person_Address_Line1"),
            ("person", "Address_Suburb", "ctl0_MainContent_Person_Address_Suburb"),
            ("person", "Address_Postcode", "ctl0_MainContent_Person_Address_Postcode"),
            ("person", "Address_Country", "ctl0_MainContent_Person_Address_Country"),
            ("person", "Address_State", "ctl0_MainContent_Person_Address_State"),
            ("person", "Address_Timezone", "ctl0_MainContent_Person_Address_TimeZone"),
            ("person", "Save", "ctl0_MainContent_checkButton"),
            ("person", "Search People", "ctl0_MainContent_SearchText"),
            ("person", "searchActiveFlag", "ctl0_MainContent_searchActiveFlag"),
            ("person", "Search User", "ctl0_MainContent_SearchButton"),
            ("person", "Search User Results", "//table[@id='ctl0_MainContent_DataList']/tbody//table/tbody/tr/td/b"),
            ("admin/causecategorytype", "Add Cause Category", "ctl0_MainContent_AddButton"),
            ("admin/causecategorytype", "Category Code", "ctl0_MainContent_CauseCategoryCode"),
            ("admin/causecategorytype", "CauseCategory Name", "ctl0_MainContent_CauseCategoryName"),
            ("admin/causecategorytype", "Active", "ctl0_MainContent_active"),
            ("admin/causecategorytype", "Billable", "ctl0_MainContent_billable"),
            ("admin/causecategorytype", "WorkTypeList", "ctl0_MainContent_workTypeList"),
            ("admin/causecategorytype", "Save", "ctl0_MainContent_EditButton"),
            ("admin/causecategorytype", "Search Cause Category", "ctl0_MainContent_SearchText"),
            ("admin/causecategorytype", "Search", "ctl0_MainContent_SearchButton"),            
            ("admin/causecategorytype", "Seach Category Results", "//table[@id='ctl0_MainContent_DataList']/tbody//table/tbody/tr/td"),
            ("serviceplan", "Add New", "//input[@value='Add New']"),
            ("serviceplan", "Contract - Work Type", "ctl0_MainContent_newWorkTypeSelection"),
            ("serviceplan", "Site", "ctl0_MainContent_SiteList"),
            ("serviceplan", "Generic Support", "ctl0_MainContent_newNameOrDept"),
            ("serviceplan", "Service Plan Instructions", "mceContentBody"),
            ("serviceplan", "Save", "ctl0_MainContent_newSave"),
            ("serviceplan/view", "Return To Search", "backToSearchFromView"),
            ("serviceplan", "WorkType Site Search Text", "ctl0_MainContent_workTypeSiteSearchText"),
            ("serviceplan", "Search Service Plans", "ctl0_MainContent_search"),
            ("serviceplan", "Search Service Plans Results", "//span[@id='ctl0_MainContent_SearchResultsSitePanel']/table/tbody/tr[2]/td[1]/a"),
            ("admin/actiontype", "Add New Action Type", "ctl0_MainContent_AddButton"),
            ("admin/actiontype", "Action Type Name", "ctl0_MainContent_name"),
            ("admin/actiontype", "Part Required", "ctl0_MainContent_requireParts"),
            ("admin/actiontype", "Part Insurance Required", "ctl0_MainContent_requirePartInstance"),
            ("admin/actiontype", "Part Movement Direction", "ctl0_MainContent_partsMovementDirection"),
            ("admin/actiontype", "Work Type", "ctl0_MainContent_workTypeList"),
            ("admin/actiontype", "Part Type Groups", "ctl0_MainContent_partTypeGroupList"),
            ("admin/actiontype", "Save", "ctl0_MainContent_EditButton"),
            ("admin/actiontype", "Search Action Types", "ctl0_MainContent_actionTypeList"),
            ("admin/actiontype", "Search", "ctl0_MainContent_SearchButton"),
            ("admin/actiontype", "Search Action Type Results", "//table[@id='ctl0_MainContent_DataList']/tbody//table/tbody/tr/td[2]"),
            ("country", "List of Countries Header", "//table[@id='ctl0_MainContent_DataList']/thead//table/tbody/tr"),
            ("country", "List of Countries body", "//table[@id='ctl0_MainContent_DataList']/tbody//table/tbody"),
            ("country", "List of Regions", "//table[@id='ctl0_MainContent_DataList']/tbody//table/tbody/tr"),
            ("country", "List of Regions Headers", "//table[@id='ctl0_MainContent_DataList']/thead//table/tbody/tr"),
            ("country", "List of Areas", "//table[@id='ctl0_MainContent_DataList']/tbody//table/tbody/tr"),
            ("country", "List of Zone Sets", "//table[@id='ctl0_MainContent_DataList']/tbody//table/tbody/tr"),
            ("country", "List of Zones", "//table[@id='ctl0_MainContent_DataList']/tbody//table/tbody/tr"),
            ("country", "List of Sites", "//table[@id='ctl0_MainContent_DataList']/tbody/tr"),
            ("admin/createuser", "Company", "ctl0_MainContent_Company"),
            ("admin/createuser", "Clone from", "ctl0_MainContent_FromUser"),
            ("admin/createuser", "First Name", "ctl0_MainContent_FirstName"),
            ("admin/createuser", "Last Name", "ctl0_MainContent_LastName"),
            ("admin/createuser", "Email", "ctl0_MainContent_Email"),
            ("admin/createuser", "User Name", "ctl0_MainContent_Username"),
            ("admin/createuser", "Password", "ctl0_MainContent_NewUserPassword"),
            ("admin/createuser", "Create", "ctl0_MainContent_AddNewButton"),
            ("admin/createuser", "UserName After Creation", "ctl0_MainContent_InfoLabel"),
            ("parttypes", "Search Part Types", "ctl0_MainContent_SearchButton"),
            ("parttypes", "List of Parts", "//table[@id='ctl0_MainContent_DataList']/tbody/tr"),
            ("parttypes", "Part Code and Name", "//table[@id='ctl0_MainContent_DataList']/tbody/tr/td/span/table//tr"),
            ("parttypes", "Type", "//tr[@class='']/td/select[contains(@id,'type')]"),
            ("parttypes", "Alias", "//tr[@class='']/td/input[contains(@id,'_alias')]"),
            ("parttypes", "Search Part Code", "ctl0_MainContent_SearchPartCode"),
            ("parttypes", "Search Part Name", "ctl0_MainContent_SearchName"),
            ("parttypes", "Search Alias Type", "ctl0_MainContent_SearchAliasType"),
            ("parttypes", "Search Alias Text", "ctl0_MainContent_SearchAliasText"),
            ("parttypes", "To Alias icon", "//input[@id='ctl0_MainContent_DataList_ctl1_ctl1']/following-sibling::a/img[contains(@title,'Alias')]"),
            ("parttypes", "", ""),
            
            ("task/logistics", "Task No", "ctl0_MainContent_taskNumber"),
            ("task/logistics", "Client Ref", "ctl0_MainContent_clientRefNumber"),
            ("task/logistics", "Serial Number", "ctl0_MainContent_serialNumber"),
            ("task/logistics", "Search Field Tasks", "ctl0_MainContent_search"),
            ("task/logistics", "Search Tasks Result", "//table[@class='DataList']/tbody/tr[1]/td[1]"),
            ("task/logistics", "Search Client Ref", "//table[@class='DataList']/tbody/tr[1]/td[2]"),
            ("task/logistics", "Tasks Result Table", "//table[@class='DataList']/tbody"),
            ("task/logistics", "Tasks Result Table Header", "//table[@class='DataList']/thead"),
            ("task/logistics", "View Status Legend", "ctl0_MainContent_changeLegendVisibility"),
            ("task/logistics", "Change Column Views", "ctl0_MainContent_changeColumnVisibilities"),
            ("task/logistics", "State", "//label[text()='State']/preceding-sibling::input"),
            ("task/logistics", "APP_END", "//label[text()='APP_END']/preceding-sibling::input"),
            ("task/logistics", "save view", "ctl0_MainContent_saveColumnBtn"),
            ("task/logistics", "No. of Tasks", "//select[@id='ctl0_MainContent_limitBy']"),
            ("task/logistics", "Total Tasks", "//div[@id='ctl0_MainContent_ListingPanel']/following-sibling::b"),
            ("calldesk", "TaskNumber", "//span[@id='ctl0_MainContent_FieldTaskNumber']/b/a"),
            ("purchaseorder", "Add New Purchase Order", "ctl0_MainContent_AddButton"),
            ("purchaseorder", "Purchase Order No", "ctl0_MainContent_addPoPanel_purchaseOrderNo"),
            ("purchaseorder", "Supplier Name", "ctl0_MainContent_addPoPanel_supplierName"),
            ("purchaseorder", "Order Status", "ctl0_MainContent_addPoPanel_OrderStatus"),
            ("purchaseorder", "Order Currency", "ctl0_MainContent_addPoPanel_OrderCurrency"),
            ("purchaseorder", "Comments", "ctl0_MainContent_addPoPanel_Comments"),
            ("purchaseorder", "Part Type", "ctl0_MainContent_addPoPanel_PartType"),
            ("purchaseorder", "Diss. Code", "ctl0_MainContent_addPoPanel_disectionCodeBox"),
            ("purchaseorder", "Quantity", "ctl0_MainContent_addPoPanel_Quantity"),
            ("purchaseorder", "Unit Cost (Ex. GST)", "ctl0_MainContent_addPoPanel_unitCost"),
            ("purchaseorder", "Add", "//input[@name='ctl0$MainContent$addPoPanel$addPurchaseOrderPart']"),
            ("purchaseorder", "Save", "//input[@name='ctl0$MainContent$addPoPanel$saveButton']"),
            ("purchaseorder", "PoNumber", "ctl0_MainContent_SearchText"),
            ("purchaseorder", "Search", "//input[@name='ctl0$MainContent$SearchButton']"),
            ("purchaseorder", "VerifyPoNumber", "//table/tbody/tr[1]/td[2]/b"),
            ("purchaseorder/reconcile", "ReconcilePoNumber", "ctl0_MainContent_poNo"),
            ("purchaseorder/reconcile", "Delivery/Invoice No", "DeliveryDocketNumber"),
            ("purchaseorder/reconcile", "Forwarded to", "ForwardedTo"),
            ("purchaseorder/reconcile", "Delivery Notes", "DeliveryNotes"),
            ("purchaseorder/reconcile", "Rec. Qty", "//table/tbody/tr[2]/td/span/div/div[5]/div[3]/input[1]"),
            ("purchaseorder/reconcile", "Part Notes", "//table/tbody/tr[2]/td/span/div/div[5]/div[4]/textarea[1]"),
            ("purchaseorder/reconcile", "Save", "//input[@name='SaveButton']"),
            ("purchaseorder/reconcile", "PoMessage", "//span[@id='ctl0_InfoMessage']"),
            ("purchaseorder/reconcile", "HistoryPartCode", "//table/tbody/tr[2]/td/span/div[3]/div[4]/div[2]/label"),
            ("report/worm", "Contract-WorkType(s)", "ctl0_MainContent_WorkTypes"),
            ("report/worm", "Preferred Time Zone", "ctl0_MainContent_TimeZone"),
            ("report/worm", "List of Areas", "ctl0_MainContent_Regions"),
            ("report/worm", "Display", "ctl0_MainContent_createWorm"),
            ("report/worm", "With Mitigation", "//input[@id='ctl0_MainContent_MitigationCount']"),
            ("ajax/?method=worm&workTypes", "WormGraphImage", "//img[@id='worm']"),
            ("report/baddatesdata", "Table", "ctl0_MainContent_tableList"),
            ("report/baddatesdata", "Limit", "ctl0_MainContent_limitList"),
            ("report/baddatesdata", "Debug", "ctl0_MainContent_debugFlag"),
            ("report/baddatesdata", "Search", "ctl0_MainContent_search"),
            ("report/baddatesdata", "BadDateMessageId", "//html/body/h1"),
            ("report/baddatesdata", "BadDateSubMessageId", "//html/body/h2"),
            
        };


    }
}
