// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BSuiteE2ERegressionTestSuite.Features.HealthAndSafety.PreStartAssessmentSurvey
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Health and Safety - Daily PreStart Form - Field Technician No Scenario and Superv" +
        "isors View", new string[] {
            "Health&Safety",
            "Pre-Start-Form"}, Description="User Journey (Field Technician):\r\nAs a Tabcorp Technician Employee working for MA" +
        "X Technical Services and using BSuite in my day to day activities,\r\nI want to re" +
        "port the issue that I have (where I have answered No in Daily prestart form) to " +
        "my supervisor to provide support to enable me to complete my Daily Pre Start Sur" +
        "vey \r\nSo that I can safely continue my work\r\nand I can evidence compliance with " +
        "the Health & Safety policies of Tabcorp while ensuring my supervisors are suppor" +
        "ting me.\r\n\r\nUser Journey (Supervisor):\r\nAs a Supervisor with Field Technicians u" +
        "sing BSuite in their day to day activities\r\nI want to  record any responses wher" +
        "e No is answered and reactivate the checklist or close it.\r\nSo that I ensure the" +
        "y can complete the daily Pre Start check list accurately and quickly and proceed" +
        " to their daily activities.\r\nand I can evidence compliance with the Health & Saf" +
        "ety policies of Tabcorp while ensuring I am supporting my team.\r\n\r\nAcceptance Cr" +
        "iteria:\r\n\r\nGiven a Field Technician answers \'No\' to a question\r\nAnd the Field Te" +
        "chnician has telephoned the Supervisor and discussed the issue\r\nWhen the Field T" +
        "echnician has responded \"No\" to a question that requires my response before prog" +
        "ressing\r\nThen I can mitigate the issue\r\nAnd confirm that the Field Technician ca" +
        "n safely proceed with work in the appropriate role for that day\r\nAnd the Supervi" +
        "sor is able to record responses on the check list and reactivate it\r\nAnd the nex" +
        "t question is enabled for the Field Technician \r\nAnd Field Technician is allowed" +
        " to proceed with the survey\r\n\r\nThe Field Technician has replied No to a critical" +
        " question on the pre start checklist. The check list has suspended and the Field" +
        " Technician cannot complete the checklist and move to On Call until their Custom" +
        "er Operations Manager has agreed a response, recorded and reactivate the checkli" +
        "st.\r\n\r\nResponds to questions where the Field Technician answers no and the Pre S" +
        "tart checklist in BSuite suspends as a result of that answer.\r\nThe supervisor wi" +
        "ll enter a response and reactivate the Pre Start checklist\r\nOnce the Checklist i" +
        "s reactivated the Field Technician can then proceed to the next question.\r\nRelat" +
        "es to Question 1,2 and 5 of the Field Technicians mobile Pre Start check list on" +
        "ly.\r\nWhere the response is No at Q5 the supervisor may manually update the Field" +
        " Technician to On Call to enable them to complete other activities ( i.e. not fi" +
        "eld tasks).", SourceFile="Features\\Health and Safety\\PreStart Assessment Survey\\Health and Safety - Daily P" +
        "reStart Form - Field Technician No Scenario and Supervisors View.feature", SourceLine=1)]
    [TechTalk.SpecRun.IgnoreAttribute()]
    public partial class HealthAndSafety_DailyPreStartForm_FieldTechnicianNoScenarioAndSupervisorsViewFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "Health&Safety",
                "Pre-Start-Form",
                "ignore"};
        
#line 1 "Health and Safety - Daily PreStart Form - Field Technician No Scenario and Supervisors View.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Health and Safety/PreStart Assessment Survey", "Health and Safety - Daily PreStart Form - Field Technician No Scenario and Superv" +
                    "isors View", "User Journey (Field Technician):\r\nAs a Tabcorp Technician Employee working for MA" +
                    "X Technical Services and using BSuite in my day to day activities,\r\nI want to re" +
                    "port the issue that I have (where I have answered No in Daily prestart form) to " +
                    "my supervisor to provide support to enable me to complete my Daily Pre Start Sur" +
                    "vey \r\nSo that I can safely continue my work\r\nand I can evidence compliance with " +
                    "the Health & Safety policies of Tabcorp while ensuring my supervisors are suppor" +
                    "ting me.\r\n\r\nUser Journey (Supervisor):\r\nAs a Supervisor with Field Technicians u" +
                    "sing BSuite in their day to day activities\r\nI want to  record any responses wher" +
                    "e No is answered and reactivate the checklist or close it.\r\nSo that I ensure the" +
                    "y can complete the daily Pre Start check list accurately and quickly and proceed" +
                    " to their daily activities.\r\nand I can evidence compliance with the Health & Saf" +
                    "ety policies of Tabcorp while ensuring I am supporting my team.\r\n\r\nAcceptance Cr" +
                    "iteria:\r\n\r\nGiven a Field Technician answers \'No\' to a question\r\nAnd the Field Te" +
                    "chnician has telephoned the Supervisor and discussed the issue\r\nWhen the Field T" +
                    "echnician has responded \"No\" to a question that requires my response before prog" +
                    "ressing\r\nThen I can mitigate the issue\r\nAnd confirm that the Field Technician ca" +
                    "n safely proceed with work in the appropriate role for that day\r\nAnd the Supervi" +
                    "sor is able to record responses on the check list and reactivate it\r\nAnd the nex" +
                    "t question is enabled for the Field Technician \r\nAnd Field Technician is allowed" +
                    " to proceed with the survey\r\n\r\nThe Field Technician has replied No to a critical" +
                    " question on the pre start checklist. The check list has suspended and the Field" +
                    " Technician cannot complete the checklist and move to On Call until their Custom" +
                    "er Operations Manager has agreed a response, recorded and reactivate the checkli" +
                    "st.\r\n\r\nResponds to questions where the Field Technician answers no and the Pre S" +
                    "tart checklist in BSuite suspends as a result of that answer.\r\nThe supervisor wi" +
                    "ll enter a response and reactivate the Pre Start checklist\r\nOnce the Checklist i" +
                    "s reactivated the Field Technician can then proceed to the next question.\r\nRelat" +
                    "es to Question 1,2 and 5 of the Field Technicians mobile Pre Start check list on" +
                    "ly.\r\nWhere the response is No at Q5 the supervisor may manually update the Field" +
                    " Technician to On Call to enable them to complete other activities ( i.e. not fi" +
                    "eld tasks).", ProgrammingLanguage.CSharp, new string[] {
                        "Health&Safety",
                        "Pre-Start-Form",
                        "ignore"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Health and Safety - Daily PreStart Form - Field Technician No Scenario and Superv" +
            "isors View", new string[] {
                "BSuite",
                "BSuite-Mobile",
                "BSuite-Website",
                "Field-Technician",
                "Supervisor",
                "GSQA-167"}, SourceLine=36)]
        public virtual void HealthAndSafety_DailyPreStartForm_FieldTechnicianNoScenarioAndSupervisorsView()
        {
            string[] tagsOfScenario = new string[] {
                    "BSuite",
                    "BSuite-Mobile",
                    "BSuite-Website",
                    "Field-Technician",
                    "Supervisor",
                    "GSQA-167"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Health and Safety - Daily PreStart Form - Field Technician No Scenario and Superv" +
                    "isors View", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 37
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 38
 testRunner.Given("I have logged into BSuite \'Mobile\' portal as a User with role \'Field Technician\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 39
 testRunner.And("I am required to complete the Pre Start Checklist for the day in mobile portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question Number",
                            "Question"});
                table39.AddRow(new string[] {
                            "1",
                            "My vehicle is roadworthy – e.g. windscreen and mirrors free of damage, all lights" +
                                " operational and tyres inflated with sufficient tread."});
#line 41
 testRunner.And("the \'first\' question of the Pre Start Checklist is displayed as follows in mobile" +
                        " portal", ((string)(null)), table39, "And ");
#line hidden
#line 44
 testRunner.When("I respond \'No\' to the \'first\' Pre Start Checklist question in mobile portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                            "Prompt Message"});
                table40.AddRow(new string[] {
                            "STOP"});
#line 45
 testRunner.Then("\'first\' prompt message is displayed to contact Supervisor as follows in mobile po" +
                        "rtal", ((string)(null)), table40, "Then ");
#line hidden
#line 48
 testRunner.And("I log off from Bsuite \'Mobile\' portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 49
 testRunner.Given("I have logged into BSuite \'Desktop\' portal as a User with role \'Service Delivery " +
                        "Manager\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 50
 testRunner.When("I have navigated to \'Tasks by Watch List\' page from \'Call Centre\' top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 51
 testRunner.Then("I click PreStart link for the \'first\' No response and reactivate it for \'Field Te" +
                        "chnician\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 52
 testRunner.And("I log off from Bsuite \'Desktop\' portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 54
 testRunner.Given("I have logged into BSuite \'Mobile\' portal as a User with role \'Field Technician\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question Number",
                            "Question"});
                table41.AddRow(new string[] {
                            "2",
                            "Are all licenses that you require for your duties / role currently valid? E.G. dr" +
                                "ivers licence, gaming licence?"});
#line 55
 testRunner.And("the \'second\' question of the Pre Start Checklist is displayed as follows in mobil" +
                        "e portal", ((string)(null)), table41, "And ");
#line hidden
#line 58
 testRunner.When("I respond \'No\' to the \'second\' Pre Start Checklist question in mobile portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                            "Prompt Message"});
                table42.AddRow(new string[] {
                            "STOP"});
#line 59
 testRunner.Then("\'second\' prompt message is displayed to contact Supervisor as follows in mobile p" +
                        "ortal", ((string)(null)), table42, "Then ");
#line hidden
#line 62
 testRunner.And("I log off from Bsuite \'Mobile\' portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 63
 testRunner.Given("I have logged into BSuite \'Desktop\' portal as a User with role \'Service Delivery " +
                        "Manager\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 64
 testRunner.When("I have navigated to \'Tasks by Watch List\' page from \'Call Centre\' top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 65
 testRunner.Then("I click PreStart link for the \'second\' No response and reactivate it for \'Field T" +
                        "echnician\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 66
 testRunner.And("I log off from Bsuite \'Desktop\' portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 68
 testRunner.Given("I have logged into BSuite \'Mobile\' portal as a User with role \'Field Technician\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question Number",
                            "Question"});
                table43.AddRow(new string[] {
                            "3",
                            "Are your tools and equipment in good condition and do you have sufficient / enoug" +
                                "h PPE?"});
#line 69
 testRunner.And("the \'third\' question of the Pre Start Checklist is displayed as follows in mobile" +
                        " portal", ((string)(null)), table43, "And ");
#line hidden
#line 72
 testRunner.When("I respond \'Yes\' to the \'third\' Pre Start Checklist question in mobile portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table44 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question Number",
                            "Question"});
                table44.AddRow(new string[] {
                            "4",
                            "Have you completed all mandatory training relevant to your Field Technicians Role" +
                                " – (e.g. Electrical safety / lifting / ladders etc.) OR are you familiar with al" +
                                "l of the SWP (Safe Work Practice) documents relevant to your role?"});
#line 74
 testRunner.Then("the \'fourth\' question of the Pre Start Checklist is displayed as follows in mobil" +
                        "e portal", ((string)(null)), table44, "Then ");
#line hidden
#line 77
    testRunner.When("I respond \'Yes\' to the \'fourth\' Pre Start Checklist question in mobile portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table45 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question Number",
                            "Question"});
                table45.AddRow(new string[] {
                            "5",
                            "I am fit for work and can perform my work without compromising the safety or heal" +
                                "th of myself or others."});
#line 79
 testRunner.Then("the \'fifth\' question of the Pre Start Checklist is displayed as follows in mobile" +
                        " portal", ((string)(null)), table45, "Then ");
#line hidden
#line 82
 testRunner.When("I respond \'No\' to the \'fifth\' Pre Start Checklist question in mobile portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table46 = new TechTalk.SpecFlow.Table(new string[] {
                            "Prompt Message"});
                table46.AddRow(new string[] {
                            "STOP"});
#line 83
 testRunner.Then("\'fifth\' prompt message is displayed to contact Supervisor as follows in mobile po" +
                        "rtal", ((string)(null)), table46, "Then ");
#line hidden
#line 86
 testRunner.And("I log off from Bsuite \'Mobile\' portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 87
 testRunner.Given("I have logged into BSuite \'Desktop\' portal as a User with role \'Service Delivery " +
                        "Manager\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 88
 testRunner.When("I have navigated to \'Tasks by Watch List\' page from \'Call Centre\' top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 89
 testRunner.Then("I click PreStart link for the \'fifth\' No response and reactivate it for \'Field Te" +
                        "chnician\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 90
 testRunner.And("I log off from Bsuite \'Desktop\' portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 92
 testRunner.Given("I have logged into BSuite \'Mobile\' portal as a User with role \'Field Technician\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 93
 testRunner.When("I check the Confirm Customer Operations Manager contacted check box for \'fifth\' n" +
                        "o response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 94
 testRunner.Then("I click the \'Submit\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
