// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BSuiteE2ERegressionTestSuite.Features.HealthAndSafety.PreStartAssessmentSurvey
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Mobile PreStart Form - Agent Technicians are not presented with Daily PreStart Fo" +
        "rm when they attempt to login via Mobile", new string[] {
            "AllTests",
            "BSuite",
            "Bsuite-Mobile",
            "Health&Safety"}, Description="\tAs a BSuite Mobile User\r\n\tI can login to BSuite Mobile portal\r\n\tSo that I can ca" +
        "rry out my tasks", SourceFile="Features\\Health and Safety\\PreStart Assessment Survey\\Mobile PreStart Form - Agen" +
        "t Technicians are not presented - Daily PreStart Form - Mobile.feature", SourceLine=1)]
    public partial class MobilePreStartForm_AgentTechniciansAreNotPresentedWithDailyPreStartFormWhenTheyAttemptToLoginViaMobileFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "AllTests",
                "BSuite",
                "Bsuite-Mobile",
                "Health&Safety"};
        
#line 1 "Mobile PreStart Form - Agent Technicians are not presented - Daily PreStart Form - Mobile.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Health and Safety/PreStart Assessment Survey", "Mobile PreStart Form - Agent Technicians are not presented with Daily PreStart Fo" +
                    "rm when they attempt to login via Mobile", "\tAs a BSuite Mobile User\r\n\tI can login to BSuite Mobile portal\r\n\tSo that I can ca" +
                    "rry out my tasks", ProgrammingLanguage.CSharp, new string[] {
                        "AllTests",
                        "BSuite",
                        "Bsuite-Mobile",
                        "Health&Safety"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void MobilePreStartForm_AgentTechniciansAreNotPresentedWithDailyPreStartFormWhenTheyAttemptToLoginViaMobile(string role, string username, string password, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "GSQA-162",
                    "PositiveTests"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Role", role);
            argumentsOfScenario.Add("Username", username);
            argumentsOfScenario.Add("Password", password);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Mobile PreStart Form - Agent Technicians are not presented with Daily PreStart Fo" +
                    "rm when they attempt to login via Mobile", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 8
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 9
 testRunner.Given("I have opened the BSuite Mobile Portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table49 = new TechTalk.SpecFlow.Table(new string[] {
                            "Role",
                            "Username",
                            "Password"});
                table49.AddRow(new string[] {
                            string.Format("{0}", role),
                            string.Format("{0}", username),
                            string.Format("{0}", password)});
#line 10
 testRunner.And("I login as a User with User Profile as follows", ((string)(null)), table49, "And ");
#line hidden
#line 13
 testRunner.When("login is successful", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 14
 testRunner.Then("The Agent Technician is NOT presented with the Daily PreStart Form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Mobile PreStart Form - Agent Technicians are not presented with Daily PreStart Fo" +
            "rm when they attempt to login via Mobile, Agent Technician", new string[] {
                "GSQA-162",
                "PositiveTests"}, SourceLine=18)]
        public virtual void MobilePreStartForm_AgentTechniciansAreNotPresentedWithDailyPreStartFormWhenTheyAttemptToLoginViaMobile_AgentTechnician()
        {
#line 8
this.MobilePreStartForm_AgentTechniciansAreNotPresentedWithDailyPreStartFormWhenTheyAttemptToLoginViaMobile("Agent Technician", "TestAgentTech154", "bsuite", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
