// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BSuiteE2ERegressionTestSuite.Features.HealthAndSafety.PreStartAssessmentSurvey
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Health and Safety - Mobile Daily PreStart Form - Field Technicians - Happy Path -" +
        " via Mobile", new string[] {
            "AllTests",
            "BSuite",
            "HealthAndSafety",
            "Pre-Start-Form"}, Description="\tAs a BSuite Mobile User\r\n\tI can login to BSuite mobile portal\r\n\tSo that I can ve" +
        "rify is Daily PreStart form is being displayed in mobile portal", SourceFile="Features\\Health and Safety\\PreStart Assessment Survey\\Pre Start Checklist - Field" +
        " Technicians Login- In Mobile - Report.feature", SourceLine=1)]
    [TechTalk.SpecRun.IgnoreAttribute()]
    public partial class HealthAndSafety_MobileDailyPreStartForm_FieldTechnicians_HappyPath_ViaMobileFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "AllTests",
                "BSuite",
                "HealthAndSafety",
                "Pre-Start-Form",
                "ignore"};
        
#line 1 "Pre Start Checklist - Field Technicians Login- In Mobile - Report.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Health and Safety/PreStart Assessment Survey", "Health and Safety - Mobile Daily PreStart Form - Field Technicians - Happy Path -" +
                    " via Mobile", "\tAs a BSuite Mobile User\r\n\tI can login to BSuite mobile portal\r\n\tSo that I can ve" +
                    "rify is Daily PreStart form is being displayed in mobile portal", ProgrammingLanguage.CSharp, new string[] {
                        "AllTests",
                        "BSuite",
                        "HealthAndSafety",
                        "Pre-Start-Form",
                        "ignore"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void HealthAndSafety_MobileDailyPreStartForm_FieldTechniciansDailyPreStartFormWillBeAvailableForFieldTechnicianInMobilePortalOnly(string role, string username, string password, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "GSQA-163",
                    "Positive-Scenario-B-Suite-Mobile",
                    "Pre-Start-Form"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Role", role);
            argumentsOfScenario.Add("Username", username);
            argumentsOfScenario.Add("Password", password);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Health and Safety - Mobile Daily PreStart Form - Field Technicians Daily PreStart" +
                    " Form will be available for Field Technician in Mobile Portal only", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 8
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table54 = new TechTalk.SpecFlow.Table(new string[] {
                            "Role",
                            "Username",
                            "Password"});
                table54.AddRow(new string[] {
                            string.Format("{0}", role),
                            string.Format("{0}", username),
                            string.Format("{0}", password)});
#line 10
 testRunner.Given("I have logged into \'BSuite Mobile\' portal as a User with following User Profile", ((string)(null)), table54, "Given ");
#line hidden
#line 14
 testRunner.When("login is successful", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 15
 testRunner.And("I am required to complete the Pre Start Checklist for the day in mobile portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table55 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question Number",
                            "Question"});
                table55.AddRow(new string[] {
                            "1",
                            "My vehicle is roadworthy – e.g. windscreen and mirrors free of damage, all lights" +
                                " operational and tyres inflated with sufficient tread."});
#line 16
 testRunner.Then("the \'first\' question of the Pre Start Checklist is displayed as follows in mobile" +
                        " portal", ((string)(null)), table55, "Then ");
#line hidden
#line 19
 testRunner.When("I respond \'Yes\' to the \'first\' Pre Start Checklist question in mobile portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table56 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question Number",
                            "Question"});
                table56.AddRow(new string[] {
                            "2",
                            "Are all licenses that you require for your duties / role currently valid? E.G. dr" +
                                "ivers licence, gaming licence?"});
#line 20
 testRunner.Then("the \'second\' question of the Pre Start Checklist is displayed as follows in mobil" +
                        "e portal", ((string)(null)), table56, "Then ");
#line hidden
#line 23
 testRunner.When("I respond \'Yes\' to the \'second\' Pre Start Checklist question in mobile portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table57 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question Number",
                            "Question"});
                table57.AddRow(new string[] {
                            "3",
                            "Are your tools and equipment in good condition and do you have sufficient / enoug" +
                                "h PPE?"});
#line 24
 testRunner.Then("the \'third\' question of the Pre Start Checklist is displayed as follows in mobile" +
                        " portal", ((string)(null)), table57, "Then ");
#line hidden
#line 27
 testRunner.When("I respond \'Yes\' to the \'third\' Pre Start Checklist question in mobile portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table58 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question Number",
                            "Question"});
                table58.AddRow(new string[] {
                            "4",
                            "Have you completed all mandatory training relevant to your Field Technicians Role" +
                                " – (e.g. Electrical safety / lifting / ladders etc.) OR are you familiar with al" +
                                "l of the SWP (Safe Work Practice) documents relevant to your role?"});
#line 28
 testRunner.Then("the \'fourth\' question of the Pre Start Checklist is displayed as follows in mobil" +
                        "e portal", ((string)(null)), table58, "Then ");
#line hidden
#line 31
 testRunner.When("I respond \'Yes\' to the \'fourth\' Pre Start Checklist question in mobile portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table59 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question Number",
                            "Question"});
                table59.AddRow(new string[] {
                            "5",
                            "I am fit for work and can perform my work without compromising the safety or heal" +
                                "th of myself or others."});
#line 32
 testRunner.Then("the \'fifth\' question of the Pre Start Checklist is displayed as follows in mobile" +
                        " portal", ((string)(null)), table59, "Then ");
#line hidden
#line 35
 testRunner.When("I respond \'Yes\' to the \'fifth\' Pre Start Checklist question in mobile portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 36
 testRunner.Then("I click the \'Submit\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Health and Safety - Mobile Daily PreStart Form - Field Technicians Daily PreStart" +
            " Form will be available for Field Technician in Mobile Portal only, Field Techni" +
            "cian", new string[] {
                "GSQA-163",
                "Positive-Scenario-B-Suite-Mobile",
                "Pre-Start-Form"}, SourceLine=39)]
        public virtual void HealthAndSafety_MobileDailyPreStartForm_FieldTechniciansDailyPreStartFormWillBeAvailableForFieldTechnicianInMobilePortalOnly_FieldTechnician()
        {
#line 8
this.HealthAndSafety_MobileDailyPreStartForm_FieldTechniciansDailyPreStartFormWillBeAvailableForFieldTechnicianInMobilePortalOnly("Field Technician", "TestField163Tech1", "bsuite", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
