// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BSuiteE2ERegressionTestSuite.Features.JobCompletion
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Job Completion - Job Cancelled via Desktop - Call Desk Manager", new string[] {
            "AllTests",
            "Bsuite",
            "BSuite-Website",
            "Job-Completion",
            "Call-Desk-Manager"}, Description="As a User with role \"Call Desk Manager\" accessing BSuite desktop portal,\r\nI am ab" +
        "le to Cancel a Task\r\n\r\nDescription", SourceFile="Features\\Job Completion\\Job Completion - Job Cancelled via Desktop - Call Desk Ma" +
        "nager.feature", SourceLine=1)]
    public partial class JobCompletion_JobCancelledViaDesktop_CallDeskManagerFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "AllTests",
                "Bsuite",
                "BSuite-Website",
                "Job-Completion",
                "Call-Desk-Manager"};
        
#line 1 "Job Completion - Job Cancelled via Desktop - Call Desk Manager.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Job Completion", "Job Completion - Job Cancelled via Desktop - Call Desk Manager", "As a User with role \"Call Desk Manager\" accessing BSuite desktop portal,\r\nI am ab" +
                    "le to Cancel a Task\r\n\r\nDescription", ProgrammingLanguage.CSharp, new string[] {
                        "AllTests",
                        "Bsuite",
                        "BSuite-Website",
                        "Job-Completion",
                        "Call-Desk-Manager"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Job Completion - Job Cancelled via Desktop - Call Desk Manager", new string[] {
                "GSQA-53"}, SourceLine=7)]
        public virtual void JobCompletion_JobCancelledViaDesktop_CallDeskManager()
        {
            string[] tagsOfScenario = new string[] {
                    "GSQA-53"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Job Completion - Job Cancelled via Desktop - Call Desk Manager", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 8
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 9
 testRunner.Given("I have logged into BSuite \'Desktop\' portal as a User with role \'Call Desk Manager" +
                        "\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 10
 testRunner.And("I have navigated to \'Call Centre\' page from the top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table95 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table95.AddRow(new string[] {
                            "Contract/WorkType",
                            "ALH Group - IT Support - Break Fix"});
#line 11
 testRunner.And("I have navigated to \'Add Task\' page and entered details as follows", ((string)(null)), table95, "And ");
#line hidden
#line 14
 testRunner.When("I click the \'Add Task\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table96 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value/Action"});
                table96.AddRow(new string[] {
                            "Site",
                            "688"});
                table96.AddRow(new string[] {
                            "Contact",
                            "Sam1234"});
                table96.AddRow(new string[] {
                            "App. Start Time",
                            "2021-11-02"});
                table96.AddRow(new string[] {
                            "App. Start Hour",
                            "00"});
                table96.AddRow(new string[] {
                            "App. Start Minute",
                            "55"});
                table96.AddRow(new string[] {
                            "App. End Time",
                            "2021-11-18"});
                table96.AddRow(new string[] {
                            "App. End Hour",
                            "00"});
                table96.AddRow(new string[] {
                            "App. End Minute",
                            "00"});
                table96.AddRow(new string[] {
                            "Serial Number",
                            "1"});
                table96.AddRow(new string[] {
                            "Position",
                            "1"});
                table96.AddRow(new string[] {
                            "Part",
                            "1000041"});
                table96.AddRow(new string[] {
                            "Part Status",
                            "Usable"});
                table96.AddRow(new string[] {
                            "Priority",
                            "1"});
                table96.AddRow(new string[] {
                            "Problem Category",
                            "Unknown"});
                table96.AddRow(new string[] {
                            "Problem Code",
                            "Unknown"});
                table96.AddRow(new string[] {
                            "Problem Desc",
                            "GSQA-53"});
#line 15
 testRunner.Then("I enter the following details in the \'Add Task - FieldTask\' page", ((string)(null)), table96, "Then ");
#line hidden
#line 33
 testRunner.When("I click the \'Save\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 34
 testRunner.Then("I fetch the task number", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 35
 testRunner.And("I click the \'Finish\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 37
 testRunner.Given("I have navigated to \'Task Status Screen\' page from \'Call Centre\' top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 38
 testRunner.And("I search the task number in \'Task Status Screen\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 39
 testRunner.And("I select \'CANCEL\' from the \'Task Status\' drop down box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 41
 testRunner.Given("I have navigated to \'Task Status Screen\' page from \'Call Centre\' top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 42
 testRunner.And("I click \'Search Field Tasks\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 43
 testRunner.When("I select the task number with status as \'SENT\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 44
 testRunner.Then("I select \'CANCEL\' from the \'Task Status\' drop down box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 46
 testRunner.Given("I have navigated to \'Call Centre\' page from the top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table97 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table97.AddRow(new string[] {
                            "Contract/WorkType",
                            "ALH Group - IT Support - Break Fix"});
#line 47
 testRunner.And("I have navigated to \'Add Task\' page and entered details as follows", ((string)(null)), table97, "And ");
#line hidden
#line 50
 testRunner.When("I click the \'Add Task\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table98 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value/Action"});
                table98.AddRow(new string[] {
                            "Site",
                            "688"});
                table98.AddRow(new string[] {
                            "Contact",
                            "Sam1234"});
                table98.AddRow(new string[] {
                            "App. Start Time",
                            "2021-11-02"});
                table98.AddRow(new string[] {
                            "App. Start Hour",
                            "00"});
                table98.AddRow(new string[] {
                            "App. Start Minute",
                            "55"});
                table98.AddRow(new string[] {
                            "App. End Time",
                            "2021-11-18"});
                table98.AddRow(new string[] {
                            "App. End Hour",
                            "00"});
                table98.AddRow(new string[] {
                            "App. End Minute",
                            "00"});
                table98.AddRow(new string[] {
                            "Serial Number",
                            "1"});
                table98.AddRow(new string[] {
                            "Position",
                            "1"});
                table98.AddRow(new string[] {
                            "Part",
                            "1000041"});
                table98.AddRow(new string[] {
                            "Part Status",
                            "Usable"});
                table98.AddRow(new string[] {
                            "Priority",
                            "1"});
                table98.AddRow(new string[] {
                            "Problem Category",
                            "Unknown"});
                table98.AddRow(new string[] {
                            "Problem Code",
                            "Unknown"});
                table98.AddRow(new string[] {
                            "Problem Desc",
                            "GSQA-53"});
#line 51
 testRunner.Then("I enter the following details in the \'Add Task - FieldTask\' page", ((string)(null)), table98, "Then ");
#line hidden
#line 69
 testRunner.When("I click the \'Save\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 70
 testRunner.Then("I fetch the task number", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 71
 testRunner.And("I click the \'Finish\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 72
 testRunner.Given("I have navigated to \'Task Status Screen\' page from \'Call Centre\' top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 73
 testRunner.And("I search the task number in \'Task Status Screen\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 74
 testRunner.And("I select \'TAKEN\' from the \'Task Status\' drop down box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 75
 testRunner.And("I have navigated to \'Task Status Screen\' page from \'Call Centre\' top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 76
 testRunner.When("I search the task number in \'Task Status Screen\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 77
 testRunner.Then("I select \'CANCEL\' from the \'Task Status\' drop down box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 79
 testRunner.Given("I have navigated to \'Call Centre\' page from the top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table99 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table99.AddRow(new string[] {
                            "Contract/WorkType",
                            "ALH Group - IT Support - Break Fix"});
#line 80
 testRunner.And("I have navigated to \'Add Task\' page and entered details as follows", ((string)(null)), table99, "And ");
#line hidden
#line 83
 testRunner.When("I click the \'Add Task\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table100 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value/Action"});
                table100.AddRow(new string[] {
                            "Site",
                            "688"});
                table100.AddRow(new string[] {
                            "Contact",
                            "Sam1234"});
                table100.AddRow(new string[] {
                            "App. Start Time",
                            "2021-11-02"});
                table100.AddRow(new string[] {
                            "App. Start Hour",
                            "00"});
                table100.AddRow(new string[] {
                            "App. Start Minute",
                            "55"});
                table100.AddRow(new string[] {
                            "App. End Time",
                            "2021-11-18"});
                table100.AddRow(new string[] {
                            "App. End Hour",
                            "00"});
                table100.AddRow(new string[] {
                            "App. End Minute",
                            "00"});
                table100.AddRow(new string[] {
                            "Serial Number",
                            "1"});
                table100.AddRow(new string[] {
                            "Position",
                            "1"});
                table100.AddRow(new string[] {
                            "Part",
                            "1000041"});
                table100.AddRow(new string[] {
                            "Part Status",
                            "Usable"});
                table100.AddRow(new string[] {
                            "Priority",
                            "1"});
                table100.AddRow(new string[] {
                            "Problem Category",
                            "Unknown"});
                table100.AddRow(new string[] {
                            "Problem Code",
                            "Unknown"});
                table100.AddRow(new string[] {
                            "Problem Desc",
                            "GSQA-53"});
#line 84
 testRunner.Then("I enter the following details in the \'Add Task - FieldTask\' page", ((string)(null)), table100, "Then ");
#line hidden
#line 102
 testRunner.When("I click the \'Save\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 103
 testRunner.Then("I fetch the task number", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 104
 testRunner.And("I click the \'Finish\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 105
 testRunner.Given("I have navigated to \'Task Status Screen\' page from \'Call Centre\' top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 106
 testRunner.And("I search the task number in \'Task Status Screen\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 107
 testRunner.And("I select \'QUEUED\' from the \'Task Status\' drop down box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 108
 testRunner.And("I have navigated to \'Task Status Screen\' page from \'Call Centre\' top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 109
 testRunner.When("I search the task number in \'Task Status Screen\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 110
 testRunner.Then("I select \'CANCEL\' from the \'Task Status\' drop down box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 112
 testRunner.Given("I have navigated to \'Call Centre\' page from the top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table101 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table101.AddRow(new string[] {
                            "Contract/WorkType",
                            "ALH Group - IT Support - Break Fix"});
#line 113
 testRunner.And("I have navigated to \'Add Task\' page and entered details as follows", ((string)(null)), table101, "And ");
#line hidden
#line 116
 testRunner.When("I click the \'Add Task\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table102 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value/Action"});
                table102.AddRow(new string[] {
                            "Site",
                            "688"});
                table102.AddRow(new string[] {
                            "Contact",
                            "Sam1234"});
                table102.AddRow(new string[] {
                            "App. Start Time",
                            "2021-11-02"});
                table102.AddRow(new string[] {
                            "App. Start Hour",
                            "00"});
                table102.AddRow(new string[] {
                            "App. Start Minute",
                            "55"});
                table102.AddRow(new string[] {
                            "App. End Time",
                            "2021-11-18"});
                table102.AddRow(new string[] {
                            "App. End Hour",
                            "00"});
                table102.AddRow(new string[] {
                            "App. End Minute",
                            "00"});
                table102.AddRow(new string[] {
                            "Serial Number",
                            "1"});
                table102.AddRow(new string[] {
                            "Position",
                            "1"});
                table102.AddRow(new string[] {
                            "Part",
                            "1000041"});
                table102.AddRow(new string[] {
                            "Part Status",
                            "Usable"});
                table102.AddRow(new string[] {
                            "Priority",
                            "1"});
                table102.AddRow(new string[] {
                            "Problem Category",
                            "Unknown"});
                table102.AddRow(new string[] {
                            "Problem Code",
                            "Unknown"});
                table102.AddRow(new string[] {
                            "Problem Desc",
                            "GSQA-53"});
#line 117
 testRunner.Then("I enter the following details in the \'Add Task - FieldTask\' page", ((string)(null)), table102, "Then ");
#line hidden
#line 135
 testRunner.When("I click the \'Save\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 136
 testRunner.Then("I fetch the task number", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 137
 testRunner.And("I click the \'Finish\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 138
 testRunner.Given("I have navigated to \'Task Status Screen\' page from \'Call Centre\' top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 139
 testRunner.And("I search the task number in \'Task Status Screen\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 140
 testRunner.And("I select \'TAKEN\' from the \'Task Status\' drop down box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 141
 testRunner.And("I have navigated to \'Task Status Screen\' page from \'Call Centre\' top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 142
 testRunner.When("I search the task number in \'Task Status Screen\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 143
 testRunner.Then("I select \'RELEASED\' from the \'Task Status\' drop down box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 144
 testRunner.When("I search the task number in \'Task Status Screen\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 145
 testRunner.Then("I select \'CANCEL\' from the \'Task Status\' drop down box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 147
 testRunner.Given("I have navigated to \'Call Centre\' page from the top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table103 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table103.AddRow(new string[] {
                            "Contract/WorkType",
                            "ALH Group - IT Support - Break Fix"});
#line 148
 testRunner.And("I have navigated to \'Add Task\' page and entered details as follows", ((string)(null)), table103, "And ");
#line hidden
#line 151
 testRunner.When("I click the \'Add Task\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table104 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value/Action"});
                table104.AddRow(new string[] {
                            "Site",
                            "688"});
                table104.AddRow(new string[] {
                            "Contact",
                            "Sam1234"});
                table104.AddRow(new string[] {
                            "App. Start Time",
                            "2021-11-02"});
                table104.AddRow(new string[] {
                            "App. Start Hour",
                            "00"});
                table104.AddRow(new string[] {
                            "App. Start Minute",
                            "55"});
                table104.AddRow(new string[] {
                            "App. End Time",
                            "2021-11-18"});
                table104.AddRow(new string[] {
                            "App. End Hour",
                            "00"});
                table104.AddRow(new string[] {
                            "App. End Minute",
                            "00"});
                table104.AddRow(new string[] {
                            "Serial Number",
                            "1"});
                table104.AddRow(new string[] {
                            "Position",
                            "1"});
                table104.AddRow(new string[] {
                            "Part",
                            "1000041"});
                table104.AddRow(new string[] {
                            "Part Status",
                            "Usable"});
                table104.AddRow(new string[] {
                            "Priority",
                            "1"});
                table104.AddRow(new string[] {
                            "Problem Category",
                            "Unknown"});
                table104.AddRow(new string[] {
                            "Problem Code",
                            "Unknown"});
                table104.AddRow(new string[] {
                            "Problem Desc",
                            "GSQA-53"});
#line 152
 testRunner.Then("I enter the following details in the \'Add Task - FieldTask\' page", ((string)(null)), table104, "Then ");
#line hidden
#line 170
 testRunner.When("I click the \'Save\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 171
 testRunner.Then("I fetch the task number", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 172
 testRunner.And("I click the \'Finish\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 173
 testRunner.Given("I have navigated to \'Task Status Screen\' page from \'Call Centre\' top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 174
 testRunner.And("I search the task number in \'Task Status Screen\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 175
 testRunner.And("I select \'TAKEN\' from the \'Task Status\' drop down box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 176
 testRunner.And("I have navigated to \'Task Status Screen\' page from \'Call Centre\' top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 177
 testRunner.When("I search the task number in \'Task Status Screen\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 178
 testRunner.Then("I select \'ONSITE\' from the \'Task Status\' drop down box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 179
 testRunner.When("I search the task number in \'Task Status Screen\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 180
 testRunner.Then("I select \'CANCEL\' from the \'Task Status\' drop down box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
