// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BSuiteE2ERegressionTestSuite.Features.JobAssignment
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Job Assignment - Field Tech Removed from Job - System Admin", new string[] {
            "AllTests",
            "Bsuite",
            "BSuite-Website",
            "System-Admin",
            "Job-Assignment"}, Description="As a User with role \"System Admin\" accessing BSuite desktop portal,\r\nI am able to" +
        " Release a Task\r\nSo that the Field Technician’s name becomes un-linked from the " +
        "task\r\nAnd the Field Technician is released from his/her responsibility as regard" +
        "s that Task.", SourceFile="Features\\Job Assignment\\Job Assignment - Field Tech Removed from Job - System Adm" +
        "in.feature", SourceLine=1)]
    public partial class JobAssignment_FieldTechRemovedFromJob_SystemAdminFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "AllTests",
                "Bsuite",
                "BSuite-Website",
                "System-Admin",
                "Job-Assignment"};
        
#line 1 "Job Assignment - Field Tech Removed from Job - System Admin.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Job Assignment", "Job Assignment - Field Tech Removed from Job - System Admin", "As a User with role \"System Admin\" accessing BSuite desktop portal,\r\nI am able to" +
                    " Release a Task\r\nSo that the Field Technician’s name becomes un-linked from the " +
                    "task\r\nAnd the Field Technician is released from his/her responsibility as regard" +
                    "s that Task.", ProgrammingLanguage.CSharp, new string[] {
                        "AllTests",
                        "Bsuite",
                        "BSuite-Website",
                        "System-Admin",
                        "Job-Assignment"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Job Assignment - Field Tech Removed from Job - System Admin", new string[] {
                "GSQA-28"}, SourceLine=8)]
        public virtual void JobAssignment_FieldTechRemovedFromJob_SystemAdmin()
        {
            string[] tagsOfScenario = new string[] {
                    "GSQA-28"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Job Assignment - Field Tech Removed from Job - System Admin", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
 testRunner.Given("I have logged into BSuite \'Desktop\' portal as a User with role \'System Admin\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 11
 testRunner.And("I have navigated to \'Call Centre\' page from the top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table82 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table82.AddRow(new string[] {
                            "Contract/WorkType",
                            "ALH Group - IT Support - Break Fix"});
#line 12
 testRunner.And("I have navigated to \'Add Task\' page and entered details as follows", ((string)(null)), table82, "And ");
#line hidden
#line 15
 testRunner.When("I click the \'Add Task\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table83 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value/Action"});
                table83.AddRow(new string[] {
                            "Site",
                            "688"});
                table83.AddRow(new string[] {
                            "Contact",
                            "Sam1234"});
                table83.AddRow(new string[] {
                            "App. Start Time",
                            "2021-11-02"});
                table83.AddRow(new string[] {
                            "App. Start Hour",
                            "00"});
                table83.AddRow(new string[] {
                            "App. Start Minute",
                            "55"});
                table83.AddRow(new string[] {
                            "App. End Time",
                            "2021-11-18"});
                table83.AddRow(new string[] {
                            "App. End Hour",
                            "00"});
                table83.AddRow(new string[] {
                            "App. End Minute",
                            "00"});
                table83.AddRow(new string[] {
                            "Serial Number",
                            "1"});
                table83.AddRow(new string[] {
                            "Position",
                            "1"});
                table83.AddRow(new string[] {
                            "Part",
                            "1000041"});
                table83.AddRow(new string[] {
                            "Part Status",
                            "Usable"});
                table83.AddRow(new string[] {
                            "Priority",
                            "1"});
                table83.AddRow(new string[] {
                            "Problem Category",
                            "Unknown"});
                table83.AddRow(new string[] {
                            "Problem Code",
                            "Unknown"});
                table83.AddRow(new string[] {
                            "Problem Desc",
                            "GSQA-28"});
#line 16
 testRunner.Then("I enter the following details in the \'Add Task - FieldTask\' page", ((string)(null)), table83, "Then ");
#line hidden
#line 34
 testRunner.When("I click the \'Save\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 35
 testRunner.Then("I fetch the task number", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 36
 testRunner.And("I click the \'Finish\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 38
 testRunner.Given("I have navigated to \'Tasks by Watch List\' page from \'Call Centre\' top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 39
 testRunner.And("I click the \'Edit Preferences\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 41
 testRunner.And("I add the technician \'TestFieldTech28\' from \'All Technicians\' to \'Technicians cur" +
                        "rently on watch list\' in \'Edit Watch List Preference\' page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 42
 testRunner.And("I add state as \'QLD\' and worktype as \'ALH Group - IT Support Break Fix\' to watch " +
                        "list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 43
 testRunner.And("I click the \'Save and Update\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 44
 testRunner.And("I click the \'Unassigned\' link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 45
 testRunner.And("I select the task number fetched for the state \'QLD\' and the worktype \'ALH Group " +
                        "- IT Support Break Fix\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 46
 testRunner.And("I select \'TAKEN\' from the \'Task Status\' drop down box for \'Field Technician\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 47
 testRunner.And("I log off from Bsuite \'Desktop\' portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 49
 testRunner.When("I have opened the BSuite Mobile Portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table84 = new TechTalk.SpecFlow.Table(new string[] {
                            "Role",
                            "Username",
                            "Password"});
                table84.AddRow(new string[] {
                            "Field Technician",
                            "TestFieldTech28",
                            "bsuite"});
#line 50
 testRunner.And("I login as a User with User Profile as follows", ((string)(null)), table84, "And ");
#line hidden
#line 53
 testRunner.Then("I click the \'Mine\' link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 54
 testRunner.And("I verify the task in My Tasks page on mobile portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 55
 testRunner.And("I log off from Bsuite \'Mobile\' portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 56
 testRunner.Given("I have logged into BSuite \'Desktop\' portal as a User with role \'System Admin\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 57
 testRunner.And("I have navigated to \'Task Status Screen\' page from \'Call Centre\' top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 58
 testRunner.And("I search the task number in \'Task Status Screen\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 59
 testRunner.And("I select \'RELEASED\' from the \'Task Status\' drop down box for \'Field Technician\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 60
 testRunner.And("I log off from Bsuite \'Desktop\' portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 62
 testRunner.When("I have opened the BSuite Mobile Portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table85 = new TechTalk.SpecFlow.Table(new string[] {
                            "Role",
                            "Username",
                            "Password"});
                table85.AddRow(new string[] {
                            "Field Technician",
                            "TestFieldTech28",
                            "bsuite"});
#line 63
 testRunner.And("I login as a User with User Profile as follows", ((string)(null)), table85, "And ");
#line hidden
#line 66
 testRunner.Then("I click the \'Mine\' link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 67
 testRunner.And("I am NOT able to view the Task number in My Tasks page on mobile portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 68
 testRunner.And("I log off from Bsuite \'Mobile\' portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
