// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BSuiteE2ERegressionTestSuite.Features.Monitoring
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Monitoring - Search And Filter Task Lists - Logistics Admin", new string[] {
            "AllTests",
            "BSuite",
            "BSuite-Website",
            "Monitoring",
            "Logistics-Admin"}, Description="As a User with role Logistics Admin accessing BSuite desktop portal,\r\nI am able t" +
        "o search the tasks with field values such as Task#, Client Ref#, and Serial#.", SourceFile="Features\\Monitoring\\Monitoring - Search  And Filter Task Lists - Logitics Admin.f" +
        "eature", SourceLine=1)]
    public partial class Monitoring_SearchAndFilterTaskLists_LogisticsAdminFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "AllTests",
                "BSuite",
                "BSuite-Website",
                "Monitoring",
                "Logistics-Admin"};
        
#line 1 "Monitoring - Search  And Filter Task Lists - Logitics Admin.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Monitoring", "Monitoring - Search And Filter Task Lists - Logistics Admin", "As a User with role Logistics Admin accessing BSuite desktop portal,\r\nI am able t" +
                    "o search the tasks with field values such as Task#, Client Ref#, and Serial#.", ProgrammingLanguage.CSharp, new string[] {
                        "AllTests",
                        "BSuite",
                        "BSuite-Website",
                        "Monitoring",
                        "Logistics-Admin"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Monitoring - Search And Filter Task Lists - Logistics Admin", new string[] {
                "GSQA-73"}, SourceLine=6)]
        public virtual void Monitoring_SearchAndFilterTaskLists_LogisticsAdmin()
        {
            string[] tagsOfScenario = new string[] {
                    "GSQA-73"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Monitoring - Search And Filter Task Lists - Logistics Admin", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
 testRunner.Given("I have logged into BSuite \'Desktop\' portal as a User with role \'Call Desk Manager" +
                        "\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
 testRunner.And("I have navigated to \'Call Centre\' page from the top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table135 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table135.AddRow(new string[] {
                            "Contract/WorkType",
                            "ALH Group - IT Support - Break Fix"});
#line 10
 testRunner.And("I have navigated to \'Add Task\' page and entered details as follows", ((string)(null)), table135, "And ");
#line hidden
#line 13
 testRunner.When("I click the \'Add Task\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table136 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value/Action"});
                table136.AddRow(new string[] {
                            "Site",
                            "688"});
                table136.AddRow(new string[] {
                            "Contact",
                            "Sam1234"});
                table136.AddRow(new string[] {
                            "App. Start Time",
                            "2021-11-02"});
                table136.AddRow(new string[] {
                            "App. Start Hour",
                            "00"});
                table136.AddRow(new string[] {
                            "App. Start Minute",
                            "55"});
                table136.AddRow(new string[] {
                            "App. End Time",
                            "2021-11-18"});
                table136.AddRow(new string[] {
                            "App. End Hour",
                            "00"});
                table136.AddRow(new string[] {
                            "App. End Minute",
                            "00"});
                table136.AddRow(new string[] {
                            "Serial Number",
                            "1"});
                table136.AddRow(new string[] {
                            "Position",
                            "1"});
                table136.AddRow(new string[] {
                            "Part",
                            "1000041"});
                table136.AddRow(new string[] {
                            "Part Status",
                            "Usable"});
                table136.AddRow(new string[] {
                            "Priority",
                            "1"});
                table136.AddRow(new string[] {
                            "Client Ref #",
                            "1"});
                table136.AddRow(new string[] {
                            "Problem Category",
                            "Unknown"});
                table136.AddRow(new string[] {
                            "Problem Code",
                            "Unknown"});
                table136.AddRow(new string[] {
                            "Problem Desc",
                            "GSQA-73"});
#line 14
 testRunner.Then("I enter the following details in the \'Add Task - FieldTask\' page", ((string)(null)), table136, "Then ");
#line hidden
#line 33
 testRunner.When("I click the \'Save\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 34
 testRunner.Then("I fetch the task number", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 35
 testRunner.And("I click the \'Finish\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 36
 testRunner.Then("I log off from Bsuite \'Desktop\' portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 37
 testRunner.Given("I have logged into BSuite \'Desktop\' portal as a User with role \'Logistics Admin\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 38
 testRunner.When("I have navigated to \'Task Status Screen\' page from \'Call Centre\' top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 39
 testRunner.Then("I search the task number in \'Task Status Screen\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 40
 testRunner.When("I have navigated to \'Task Status Screen\' page from \'Call Centre\' top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 41
 testRunner.Then("I search the ClientRef number in \'Task Status Screen\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 42
 testRunner.When("I have navigated to \'Task Status Screen\' page from \'Call Centre\' top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 43
 testRunner.Then("I search the Serial number in \'Task Status Screen\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
