// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BSuiteE2ERegressionTestSuite.Features.Monitoring
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Monitoring - Task Lists - Call Desk Manager", new string[] {
            "AllTests",
            "BSuite",
            "BSuite-Website",
            "Monitoring",
            "Call-Desk-Manager"}, Description="As a User with role Call Desk Manager accessing BSuite desktop portal,\r\nI am able" +
        " to monitor tasks and agent/technician activities.", SourceFile="Features\\Monitoring\\Monitoring - Task Lists - Call Desk Manager.feature", SourceLine=1)]
    public partial class Monitoring_TaskLists_CallDeskManagerFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "AllTests",
                "BSuite",
                "BSuite-Website",
                "Monitoring",
                "Call-Desk-Manager"};
        
#line 1 "Monitoring - Task Lists - Call Desk Manager.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Monitoring", "Monitoring - Task Lists - Call Desk Manager", "As a User with role Call Desk Manager accessing BSuite desktop portal,\r\nI am able" +
                    " to monitor tasks and agent/technician activities.", ProgrammingLanguage.CSharp, new string[] {
                        "AllTests",
                        "BSuite",
                        "BSuite-Website",
                        "Monitoring",
                        "Call-Desk-Manager"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Monitoring - Task Lists - Call Desk Manager", new string[] {
                "GSQA-68"}, SourceLine=6)]
        public virtual void Monitoring_TaskLists_CallDeskManager()
        {
            string[] tagsOfScenario = new string[] {
                    "GSQA-68"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Monitoring - Task Lists - Call Desk Manager", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
 testRunner.Given("I have logged into BSuite \'Desktop\' portal as a User with role \'Call Desk Manager" +
                        "\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
 testRunner.And("I have navigated to \'Tasks by Watch List\' page from \'Call Centre\' top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
 testRunner.And("I click the \'Edit Preferences\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 11
 testRunner.And("I add the technician \'TestAgentTechnician1\' from \'All Agents\' to \'Agents currentl" +
                        "y on watch list\' in \'Edit Watch List Preference\' page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 12
 testRunner.And("I add the technician \'TestAgentTechnician2\' from \'All Agents\' to \'Agents currentl" +
                        "y on watch list\' in \'Edit Watch List Preference\' page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 13
 testRunner.And("I add the technician \'TestFieldTechnician3\' from \'All Technicians\' to \'Technician" +
                        "s currently on watch list\' in \'Edit Watch List Preference\' page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 14
 testRunner.And("I add the technician \'TestFieldTechnician4\' from \'All Technicians\' to \'Technician" +
                        "s currently on watch list\' in \'Edit Watch List Preference\' page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 15
 testRunner.And("I add state as \'ACT\' and worktype as \'ALH Group - IT Support Break Fix\' to watch " +
                        "list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 16
 testRunner.And("I add state as \'QLD\' and worktype as \'ALH Group - IT Support Break Fix\' to watch " +
                        "list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 17
 testRunner.And("I add state as \'ACT\' and worktype as \'ALH Group - IT Support Break Fix\' to watch " +
                        "list for pending tasks", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 18
 testRunner.And("I add state as \'QLD\' and worktype as \'ALH Group - IT Support Break Fix\' to watch " +
                        "list for pending tasks", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 19
 testRunner.And("I click the \'Save and Update\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 20
 testRunner.When("I have navigated to \'Tasks by Watch List\' page from \'Call Centre\' top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table128 = new TechTalk.SpecFlow.Table(new string[] {
                            "Tabs"});
                table128.AddRow(new string[] {
                            "Assigned to Techs"});
                table128.AddRow(new string[] {
                            "Assigned to Agents"});
                table128.AddRow(new string[] {
                            "Unassigned"});
                table128.AddRow(new string[] {
                            "Pending"});
#line 21
 testRunner.Then("I verify the \'Tasks by Watch List\' page has the following tabs", ((string)(null)), table128, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table129 = new TechTalk.SpecFlow.Table(new string[] {
                            "Buttons"});
                table129.AddRow(new string[] {
                            "Full Screen Mode"});
                table129.AddRow(new string[] {
                            "Edit Preferences"});
                table129.AddRow(new string[] {
                            "Show Legend"});
#line 27
 testRunner.And("I verify the \'Tasks by Watch List\' page has the following buttons", ((string)(null)), table129, "And ");
#line hidden
#line 32
 testRunner.And("I verify \'TestFieldTechnician3\' is displayed under \'Technicians\' on \'Assigned to " +
                        "Techs\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 33
 testRunner.And("I verify \'TestFieldTechnician4\' is displayed under \'Technicians\' on \'Assigned to " +
                        "Techs\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 34
 testRunner.And("I verify \'Pre Start\' status on \'Assigned to Techs\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 35
 testRunner.And("I verify \'ONSITE\' status on \'Assigned to Techs\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 36
 testRunner.And("I verify \'Assigned Tasks\' status on \'Assigned to Techs\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 37
 testRunner.When("I click the \'Assigned to Agents\' link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 38
 testRunner.Then("I verify \'TestAgentTechnician1\' is displayed under \'Agents/Clients\' on \'Assigned " +
                        "to Agents\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 39
 testRunner.And("I verify \'TestAgentTechnician2\' is displayed under \'Agents/Clients\' on \'Assigned " +
                        "to Agents\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 40
 testRunner.And("I verify \'Pre Start\' status on \'Assigned to Agents\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 41
 testRunner.And("I verify \'ONSITE\' status on \'Assigned to Agents\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 42
 testRunner.And("I verify \'Assigned Tasks\' status on \'Assigned to Agents\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 43
 testRunner.When("I click the \'Unassigned\' link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 44
 testRunner.Then("I verify the \'State\' \'ACT\' added to watch list under \'Unassigned\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 45
 testRunner.And("I verify the \'WorkType\' \'ALH Group - IT Support Break Fix\' added to watch list un" +
                        "der \'Unassigned\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 46
 testRunner.And("I verify \'Unassigned Tasks\' status on \'Unassigned\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 47
 testRunner.When("I click the \'Pending\' link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 48
 testRunner.Then("I verify the \'State\' \'ACT\' added to watch list under \'Pending\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 49
 testRunner.And("I verify the \'WorkType\' \'ALH Group - IT Support Break Fix\' added to watch list un" +
                        "der \'Pending\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 50
 testRunner.And("I verify \'Pending Tasks\' status on \'Pending\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 51
 testRunner.Given("I have navigated to \'Task Status Screen\' page from the top menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 52
 testRunner.When("I click \'Search Field Tasks\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 53
 testRunner.Then("I verify that a list of all active tasks is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 54
 testRunner.When("I select the checkbox \'View Status Legend\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 55
 testRunner.Then("I verify for color-coded technician statuses are displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 56
 testRunner.Given("I select the checkbox \'View Status Legend\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 57
 testRunner.And("I search the task number in \'Task Status Screen\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 58
 testRunner.And("I select the checkbox \'Change Column Views\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 59
 testRunner.And("I select the checkbox \'State\' on Change Column Views", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 60
 testRunner.And("I deselect the checkbox \'APP_END\' on Change Column Views", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 61
 testRunner.When("I click the \'save view\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 62
 testRunner.Then("I verify that the column \'State\' is \'viewed\' as desired", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 63
 testRunner.And("I deselect the checkbox \'State\' on Change Column Views", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 64
 testRunner.And("I select the checkbox \'APP_END\' on Change Column Views", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 65
 testRunner.And("I click the \'save view\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
